### ISSUE TITLE
Count issue with PHP 7.2.3

### ISSUE THREAD

**Issue by danlinx** [thesoftwarefanatics/php-html-parser#12]
Doesn't work with 7.2.3

`count(): Parameter must be an array or an object that implements Countable`

Selector.php on line 171

This is where it's failing : 
`if (count($rule['tag']) > 0 &&
            count($rule['key']) > 0 &&`

`count` can't be used to count non-countable types from 7.2

[Check here](http://php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types)

**Comment by danlinx** [comment]
I can see you fixed this in the commit below, but I installed with composer this evening and that commit isn't present, still had the old count code. Just updated the file myself and it's working fine. If anybody else is having this problem just implement the following commit on Selector.php

[28c7dda](https://github.com/thesoftwarefanatics/php-html-parser/commit/28c7ddabbe242b5cdfc4c14cf2fa181e72b53e32)

**Comment by alcaeus** [comment]
As you can see in the commit header, the commit you referenced is already part of the 1.8.0 release, which brings me to my question: did you maybe install the original library (`paquettg/php-html-parser`) or this forked version (`thesoftwarefanatics/php-html-parser`)? I'm asking because installing the forked version installs the correct version that also works on PHP 7.2:
```
composer require thesoftwarefanatics/php-html-parser
Using version ^1.8 for thesoftwarefanatics/php-html-parser
[...]
  - Installing thesoftwarefanatics/php-html-parser (1.8.0): Downloading (100%)         
```

Applying commits manually to installed composer packages is something you should avoid. Instead, the issue should be fixed upstream (which it was).
